src/Entity/Sliders.php
<?php

namespace App\Entity;

use App\Repository\SlidersRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SlidersRepository::class)
 */
class Sliders
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $EnAvant;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $nanme;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url_img;

    /**
     * @ORM\Column(type="text")
     */
    private $descript;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEnAvant(): ?bool
    {
        return $this->EnAvant;
    }

    public function setEnAvant(bool $EnAvant): self
    {
        $this->EnAvant = $EnAvant;

        return $this;
    }

    public function getNanme(): ?string
    {
        return $this->nanme;
    }

    public function setNanme(string $nanme): self
    {
        $this->nanme = $nanme;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUrlImg(): ?string
    {
        return $this->url_img;
    }

    public function setUrlImg(string $url_img): self
    {
        $this->url_img = $url_img;

        return $this;
    }

    public function getDescript(): ?string
    {
        return $this->descript;
    }

    public function setDescript(string $descript): self
    {
        $this->descript = $descript;

        return $this;
    }
}

templates/components/body/aside.html.twig
                    <aside class='text-white'>
                        <nav class="p-3 bg-dark row">
                            <div class=' col-md-12' id="login">
                                {% if app.user %}
                                    {# Si l'utilisateur est connecter #}                        
                                    {% if app.user.IsVerified %}
                                        {# Si l'utilisateur a valider son compte #} 
                                            <img src="{{ app.user.img }}" alt="Votre photo de profil"  class="img-fluid rounded">
                                            <p class="text-center p-1 text-info border rounded border-success ">{{ app.user.email }}</p>
                                            <div class=" d-md-block text-md-center d-sm-flex justify-content-sm-center p-3 border rounded border-info">
                                                <a class='btn btn-outline-info mb-3' href='{{ path("profil_index") }}'><i class="fas fa-user mr-3"></i> Mon profil</a>
                                                <a class='btn btn-danger' href='{{ path("app_logout") }}'><i class="fas fa-sign-out-alt mr-3"></i> Se déconnecter</a>
                                            </div>
                                    {% else %}
                                    {# Si l'utilisateur n'a pas valider son compte #}
                                        <img src="{{ app.user.img }}" alt="photo de profil de {{ app.user.email }}" class="img-fluid rounded text-center">
                                        <p class="p-1  text-center text-info border rounded border-danger">
                                            ({{ app.user.email }})
                                        </p>
                                        <p class="text-center">
                                            <a class='btn btn-outline-danger' href='{{ path("app_logout") }}'><i class="fas fa-sign-out-alt"></i> Se déconnecter</a>
                                        </p>
                                {% endif %}
                                {% else %}
                                {# Si l'utilisateur est pas connecter #}
                                <div class="text-center" id="login">
                                    <div class=" d-md-block text-md-center d-sm-flex justify-content-sm-center p-3 border rounded border-warning">
                                        <a href="{{path('app_register')}}" class="mb-3 btn btn-info"><i class="fas fa-user-plus"></i> Inscription</a><br>
                                        <a href="{{path('app_login')}}" class="btn btn-outline-info"><i class="fas fa-user-check"></i> Connexion</a>
                                    </div>
                                </div>
                        {% endif %}
                            </div>
                            <div class="col-12 text-center">
                                {{ 
                                    render(controller(
                                    'App\\Controller\\SearchController::search'
                                    )) 
                                }} 
                            </div>
                        </nav>
                    </aside>

templates/components/body/slider.html.twig
<div class="card">
  {% for slider in sliders %}
  {% if slider %}
    <h6 class="card-header text-center text-white p-3 bg-info">Catégories du mois</h6>
    <a href='/categorys/{{ slider.id }}'><img class="card-body" height="200px" src="{{ slider.urlImg }}" alt="{{ slider.descript }}"></a>
    <h4 class="text-info text-center">{{ slider.name }}</h4>
    <p class='card-description text-center'>{{ slider.descript }}</p>
  {% else %}
  <div class="text-center">
    <p class="text-white">Nous n'avons pas mis le sliders du mois actuellement.</p>
  </div>
  {% endif %}
{% endfor %}
</div>