src/Entity/Prestataire.php
<?php

namespace App\Entity;

use App\Repository\PrestataireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PrestataireRepository::class)
 */
class Prestataire
{
   /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }}

src/Entity/Prestataires.php
<?php

namespace App\Entity;

use App\Repository\PrestatairesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PrestatairesRepository::class)
 */
class Prestataires
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=125)
     */
    private $website;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $number_phone;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $number_tva;

    /**
     * @ORM\Column(type="string")
     */
    private $url_logo;

    /**
     * @ORM\Column(type="text")
     */
    private $desc_short;

    /**
     * @ORM\Column(type="text")
     */
    private $desc_long;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_create;


    /**
     * @ORM\Column(type="boolean")
     */
    private $is_public;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categoryService;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $numStreet;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nameCity;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nameSteet;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numPostal;


    /**
     * @ORM\Column(type="integer")
     */
    private $num_like;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_comment;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="prestataires")
     */
    private $User;

    public function __construct()
    {

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }


    public function getUrlLogo(): ?string
    {
        return $this->url_logo;
    }

    public function setUrlLogo(string $url_logo): self
    {
        $this->url_logo = $url_logo;

        return $this;
    }

    public function getDescShort(): ?string
    {
        return $this->desc_short;
    }

    public function setDescShort(string $desc_short): self
    {
        $this->desc_short = $desc_short;

        return $this;
    }

    public function getDescLong(): ?string
    {
        return $this->desc_long;
    }

    public function setDescLong(string $desc_long): self
    {
        $this->desc_long = $desc_long;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }


    public function getNumberPhone(): ?string
    {
        return $this->number_phone;
    }

    public function setNumberPhone(?string $number_phone): self
    {
        $this->number_phone = $number_phone;

        return $this;
    }

    public function getNumberTva(): ?string
    {
        return $this->number_tva;
    }

    public function setNumberTva(?string $number_tva): self
    {
        $this->number_tva = $number_tva;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(bool $is_public): self
    {
        $this->is_public = $is_public;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategoryService(): ?string
    {
        return $this->categoryService;
    }

    public function setCategoryService(string $categoryService): self
    {
        $this->categoryService = $categoryService;

        return $this;
    }

    public function getNumStreet(): ?int
    {
        return $this->numStreet;
    }

    public function setNumStreet(int $numStreet): self
    {
        $this->numStreet = $numStreet;

        return $this;
    }

    public function getNameCity(): ?string
    {
        return $this->nameCity;
    }

    public function setNameCity(string $nameCity): self
    {
        $this->nameCity = $nameCity;

        return $this;
    }

    public function getNameSteet(): ?string
    {
        return $this->nameSteet;
    }

    public function setNameSteet(string $nameSteet): self
    {
        $this->nameSteet = $nameSteet;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): self
    {
        $this->Country = $Country;

        return $this;
    }

    public function getNumPostal(): ?string
    {
        return $this->numPostal;
    }

    public function setNumPostal(string $numPostal): self
    {
        $this->numPostal = $numPostal;

        return $this;
    }


    public function getNumLike(): ?int
    {
        return $this->num_like;
    }

    public function setNumLike(int $num_like): self
    {
        $this->num_like = $num_like;

        return $this;
    }

    public function getNumComment(): ?int
    {
        return $this->num_comment;
    }

    public function setNumComment(int $num_comment): self
    {
        $this->num_comment = $num_comment;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/PrestatairesType.php
<?php

namespace App\Form;

use App\Entity\Prestataires;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrestatairesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('name')->add('website')->add('price')->add('numTva')->add("numStreet")->add("nameSteet")->add('nameCity')->add("country")->add('numPostal');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Prestataires::class,
        ]);
    }
}

src/Controller/Admin/PrestatairesController.php
<?php

namespace App\Controller\Admin;

use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PrestatairesController extends AbstractDashboardController
{
    /**
     * @Route("/gestion", name="gestion")
     */
    public function index(): Response
    {
        return $this->render('admin/gestion.html.twig');
        return parent::index();
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('Bien Etre');
    }

    public function configureMenuItems(): iterable
    {
        return [
            MenuItem::section('<p class="text-info">Listes de toutes les pages</p>'),
            MenuItem::linkToUrl('Homepage', 'fa fa-home', '../'),
            MenuItem::linkToUrl('About', 'fa fa-info','/about'),
            MenuItem::linkToUrl('Contact', 'fa fa-envelope', '/contact'),
            MenuItem::linkToUrl('Gestion', 'fa fa-cogs', '/gestion'),

            MenuItem::section('<p class="text-info">Catégories de services</p>'),
            MenuItem::linkToUrl('Listes services', 'fa fa-list', '/categorys'),
            MenuItem::linkToUrl('Ajouter un service', 'fa fa-plus', '/categorys/add'),
            
            MenuItem::section('<p class="text-info">Prestation</p>'),
            MenuItem::linkToUrl('Ajouter une prestation', 'fa fa-plus', '/add'), 

            MenuItem::linkToUrl('Listes des utilisateurs', 'fa fa-list', '/'),  
        ];
    }
}

src/Controller/PrestatairesController.php
<?php

namespace App\Controller;

use App\Entity\CategorieDeServices;
use App\Entity\Prestataires;
use App\Entity\Categorys;
use App\Entity\User;
use App\Entity\Sliders;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class PrestatairesController extends AbstractController
{
    /**
     * @Route("/prestataires", name="prestataires_index")
     */
    public function index(EntityManagerInterface $entitymanager, Request $request): Response
    {
        
        $repository = $entitymanager->getRepository(Prestataires::class);
        $prestataires = $repository->findLatest();
        
        $repository = $entitymanager->getRepository(Categorys::class);
        $categorys = $repository->findLatest();
        
        $repository = $entitymanager->getRepository(Sliders::class);
        $sliders = $repository->findLatest();

        $repository = $entitymanager->getRepository(User::class);
        $user = $repository->findLatest();
        
        return $this->render('prestataires/index.html.twig', [
            "categorys" => $categorys,
            "prestataires" => $prestataires,
            "sliders" => $sliders,
            "user" => $user,
        ]);
    }
    /**
     * @Route("/prestataires/{id}", name="prestataires_show")
     */
    public function show(Prestataires $prestataire, EntityManagerInterface $entitymanager): Response
    {
        $repository = $entitymanager->getRepository(Categorys::class);
        $categorys = $repository->findLatest();

        $repository = $entitymanager->getRepository(Prestataires::class);
        $prestataires = $repository->findLatest();
        
        $repository = $entitymanager->getRepository(Sliders::class);
        $sliders = $repository->findLatest();

        $repository = $entitymanager->getRepository(User::class);
        $user = $repository->findLatest();

        return $this->render('prestataires/show.html.twig', [
            "prestataire" => $prestataire,
            "prestataires" => $prestataires,
            "categorys" => $categorys,
            "sliders" => $sliders,
            "user" => $user,
        ]);
    }
    /**
     * @Route("/prestataires/{id}/edit", name="prestataires_edit",  methods={"GET"})
     */
    public function edit(Prestataires $prestataire, EntityManagerInterface $entitymanager): Response
    {
        $repository = $entitymanager->getRepository(Categorys::class);
        $categorys = $repository->findLatest();

        $repository = $entitymanager->getRepository(Prestataires::class);
        $prestataires = $repository->findLatest();
        
        $repository = $entitymanager->getRepository(Sliders::class);
        $sliders = $repository->findLatest();

        $repository = $entitymanager->getRepository(User::class);
        $user = $repository->findLatest();
        
        return $this->render('prestataires/edit.html.twig', [
            "prestataire" => $prestataire,
            "prestataires" => $prestataires,
            "categorys" => $categorys,
            "sliders" => $sliders,
            "user" => $user,
        ]);
    }
    /**
     * @Route("/prestataires/{id}/delete", name="prestataires_delete",  methods={"GET"})
     */
    public function delete(Prestataires $prestataire, EntityManagerInterface $entitymanager): Response
    {
        $repository = $entitymanager->getRepository(Categorys::class);
        $categorys = $repository->findLatest();

        $repository = $entitymanager->getRepository(Prestataires::class);
        $prestataires = $repository->findLatest();
        
        $repository = $entitymanager->getRepository(Sliders::class);
        $sliders = $repository->findLatest();
        $repository = $entitymanager->getRepository(User::class);
        $user = $repository->findLatest();
        return $this->render('prestataires/show.html.twig', [
            "prestataire" => $prestataire,
            "prestataires" => $prestataires,
            "categorys" => $categorys,
            "sliders" => $sliders,
            "user" => $user,
        ]);
    }

    public function searchBar(EntityManagerInterface $entitymanager): Response
    {
       

        $repository = $entitymanager->getRepository(Prestataires::class);
        $prestataires = $repository->findLatest();

        $repository = $entitymanager->getRepository(Services::class);
        $services = $repository->findLatest();

        $repository = $entitymanager->getRepository(User::class);
        $user = $repository->findOneBy(
            array('id' => '1')
        );

        $repository = $entitymanager->getRepository(Sliders::class);
        $sliders = $repository->findBy(
            array('id' => '1')
        );

        $repository = $entitymanager->getRepository(Categorys::class);
        $categorys = $repository->findLatest();

        $form = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('prestataires.handleSearch'))
            ->add('Rechercher', TextType::class, [
                'attr'=> [
                    'class' => 'form-control text-info'
                ]
            ])
            ->add('recherche', SubmitType::class, [
                'attr'=> [
                    'class' => 'btn btn-success'
                ]
            ])
            ->getForm();

        return $this->render('search/searchBar.html.twig', [
            "categorys" => $categorys,
            "sliders" => $sliders,
            "services" => $services,
            "prestataires" => $prestataires,
            "user" => $user, 
            'form' => $form->createView()
        ]);
    }

    // /**
    // * @Route('/handleSeach' name='handleSearch', methods={"POST"})
    // * @param Request $request
    // */

    // public function handleSearch(Request $request)
    // {
         
    // }
}

templates/prestataires/_delete_form.html.twig
<form method="post" action="{{ path('prestataires_delete', {'id': prestataire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prestataire.id) }}">
    <button class="btn btn-danger">Effacer</button>
</form>

templates/prestataires/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/prestataires/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {% if app.user %}
        Profil de {{ app.user.email }}
    {% else %}
        Accès refuser !
    {% endif %}
{% endblock %}
{% block body %}

{% if app.user %}
{% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_USER') and app.user.id ) %}
<div class="d-flex justify-content-center">
    {{ include('profil/_delete_form.html.twig') }}
</div>
{% endif %}
<div class='row p-3 m-1'>
    <div class='col-12 p-2'>
        <div class="card text-center">  
            <h3 class='text-center text-info p-2 '>Modifier mon profil</h3>
            <img class="card-img-top" src="{{ app.user.img }}" height="200px" alt="{{ app.user.email }} image of profil">
            <div class="card-body">
                <h5 class="card-title p-1"><a class='text-white' href='profil/{{ app.user.id }}'>{{ app.user.email }}</a></h5>
                
            Rôles : 
            {% for role in app.user.roles %}  
                {% if role == 'ROLE_PRESTATAIRE' %}
                <p class="card ">
                    <span class="bg-dark text-white p-2 mb-1">Prestataire</span>
                </p>
                {% elseif not role == 'ROLE_ADMIN' %}
                <p class="card ">
                    <span class="bg-dark text-white p-2 mb-1">Administrateur</span>
                </p>
                {% elseif not role == 'ROLE_USER' %}
                <p class="card ">
                    <span class="bg-dark text-white p-2 mb-1">Utilisateur</span>
                </p>
                {% elseif not role == 'ROLE_INTERNAUTE' %}
                <p class="card ">
                    <span class="bg-dark text-white p-2 mb-1">Internaute</span>
                </p>
                {% endif %}
            {% endfor %}    
                {% if is_granted('ROLE_ADMIN') %}
                    Password : <p class="card ">{{ app.user.password }}</p>
                Nombre d'essai infructueux : <p class="card ">{{ app.user.nbEssaisInfructueux }}</p>
                Est-t'il vérifier ? 
                <p class="card">
                    {% if app.user.isVerified == 0 %}
                        <b class="text-danger">Ce compte n'a pas été activer par l'utilisateur.</b>
                    {% else %}
                        <b class="text-success">Ce compte à été activer.</b>
                    {% endif %}
                </p>
                Est-il banni ?
                <p class="card ">
                    {% if app.user.banni == 0 %}
                        <b class="text-success">Ce compte n'est pas banni.</b>
                    {% else %}
                        <b class="text-danger">Ce compte à été banni.</b>
                    {% endif %}
                </p>
                {% endif %}
                Date d'inscription<p class="card bg-dark text-white">{{ app.user.inscription|date }}</p>
            </div>
            <div class="card-body">
                <h3 class="h3 text-info">Listes des prestations</h3>
            {% if is_granted('ROLE_ADMIN') %}
            {% for prestataire in prestataires %}
                {% if not prestataire.user.id == app.user.id %}
                        <div class="card bg-dark text-info p-2 mb-3 ">
                            <div class="row">
                                <div class="col-md-4 col-sm-12">
                                    <img class="card-img-top" src="{{ prestataire.urlLogo }}" height="200px" alt="{{ prestataire.name }} image of profil">
                                </div>
                                <div class="col-md-8 col-sm-12">
                                    <p class="text-info p-2 mb-1">Nom : {{ prestataire.name }}</p>
                                    <p class="text-info p-2 mb-1">Téléphone : {{ prestataire.numberPhone }}</p>
                                    <p class="text-info p-2 mb-1">Adresse :{{ prestataire.numStreet }} {{ prestataire.namesteet }}</p>
                                    <p class="text-info p-2 mb-1">Code postal : {{ prestataire.numPostal }}</p>
                                    <p class="text-info p-2 mb-1">Ville : {{ prestataire.nameCity }}</p>
                                    <p class="text-info p-2 mb-1">Type de prestation : {{ prestataire.categoryService }}</p>
                                </div>
                                <div class="col-12">
                                    <div class="d-flex justify-content-center">
                                        <a href="prestataire/{{ prestataire.id }}" class="btn btn-info mr-2">Voir</a>
                                        <a href="prestataire/{{ prestataire.id }}/edit" class="btn btn-warning mr-2">Modifier</a>
                                        <a href="prestataire/{{ prestataire.id }}/delete" class="btn btn-danger">Supprimer</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                {% endif %}
            {% endfor %}
        {% else %}
        {% if is_granted('ROLE_INTERNAUTE') %}
        <div class="card bg-dark text-info p-2 mb-3 ">
            <code> Vous n'avez pas cette option en tant qu'internaute !</code>
        </div>
        {% elseif is_granted('ROLE_PRESTATAIRE') %}
        <div class="card bg-dark text-info p-2 mb-3 ">
            <code>Vous n'avez pas crée de prestation !</code>
        </div>
        {% else %}
        <div class="card bg-dark text-info p-2 mb-3 ">
            <code>Il y a une erreur dans les requêtes des cards </code>
        </div>
        {% endif %}
    {% endif %}

            </div>
            <a href="/prestataires/new" class="btn btn-info">Ajouter une prestataire</a>
    </div>
    {% else %}
    <div class="alert alert-danger text-center">
        <h3>Vous devez êtes connecter pour accéder à cette page !</h3>
    </div>
    {% endif %}
{% endblock %}

templates/prestataires/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Listes des pertataires{% endblock %}
{% block body %}
<h3 class='text-center text-info p-2 bg-white '>Tout les prestataires disponible</h3>
<div class='row p-3 m-1'>
{% for prestataire in prestataires %}
    <div class='col-4 p-2'>
        <div class="card text-center">
            <img class="card-img-top" src="{{ prestataire.urlLogo }}" alt="{{ prestataire.name }} image of logo">
            <div class="card-body">
                <h5 class="card-title bg-dark p-1"><a class='text-white' href='prestataires/{{ prestataire.id }}'>{{ prestataire.name }}</a></h5>
                <p class="card ">{{prestataire.descShort}}</p>
                <Adresse class='card bg-dark text-white'>
                        {{ prestataire.numStreet }}, {{ prestataire.nameSteet }} <br>
                        {{ prestataire.numPostal }} {{ prestataire.nameCity }} <br></address>
                <a href="prestataires/{{ prestataire.id }}" class="btn btn-info">Voir</a>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

templates/prestataires/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}prestataire | {{ prestataire.name }}{% endblock %}
{% block body %}
    <h3 class='text-center text-info p-2 bg-white '>{{ prestataire.name }}</h3>
    <p class=' m-3 text-dark bg-white text-center'>Created : {{ prestataire.dateCreate|date }}</p>
    {% if is_granted("ROLE_ADMIN") or (is_granted("ROLE_PRESTATAIRE") and app.user.id == prestataire.user.id) %}
    <div class='text-dark bg-white text-center d-flex p-1'>   
        <a class=' mr-2 btn btn-warning' href="{{ path('prestataires_edit', {'id': prestataire.id}) }}">Modifier</a>
        {{ include('prestataires/_delete_form.html.twig') }}
    </div>
    {% endif %}
    <div class='row'>
        <div class='col-4'>
            <img class='bg-white p-1 mt-2' src='{{ prestataire.urlLogo }}'></img>
        </div>    
        <div class='col-8'>
            <table class="table text-white">
        <tbody>
            {% if is_granted("ROLE_ADMIN") or (is_granted("ROLE_PRESTATAIRE") and app.user.id == prestataire.user.id) %}
            <tr>
                <th>ID</th>
                <td><code>{{ prestataire.id }}<code></td>
            </tr>
            <tr>
                <th>Crée par</th>
                <td>{{ prestataire.user.email }}</td>
            </tr>
            {% endif %}
            <tr>
                <th>Nom</th>
                <td>{{ prestataire.name }}</td>
            </tr>
            <tr>
                <th>Numéro de TVA</th>
                <td><b><code> {{ prestataire.numberTva }} </code></b></td>
            </tr>
            <tr>
                <th>Site web</th>
                <td><a class='link text-info' href='{{ prestataire.website }}'>{{ prestataire.website }}</a></td>
            </tr>
            <tr>
                <th>Prix de la prestation</th>
                <td>{{ prestataire.price }} €</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ prestataire.descLong }}</td>
            </tr>
            <tr>
                <th>Categories de services</th>
                <td>{{ prestataire.categoryService }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>
                    <address>
                        <b>{{ prestataire.name }}</b> <br>
                        {{ prestataire.numStreet }}, {{ prestataire.nameSteet }} <br>
                        {{ prestataire.numPostal }} {{ prestataire.nameCity }} <br>
                    </address>
                </td>
            </tr>
        </tbody>
    </table>

        </div>
    </div>
    <a class='btn btn-lg text-white' href="{{ path('prestataires_index') }}"><i class="fas fa-arrow-alt-circle-left"></i></a>
{% endblock %}